"""JSON API blueprint, version 1.

Routes are registered under /api/v1/. OpenAPI spec is auto-generated by
APIFlask at /api/v1/openapi.json with Swagger UI at /api/v1/docs.

The API uses bearer-token auth for endpoints that require identity, and
leaves public endpoints unauthenticated. Tokens are issued by
POST /api/v1/auth/token in exchange for a username + password.
"""
from apiflask import APIBlueprint

api_bp = APIBlueprint('api', __name__, url_prefix='/api/v1', tag='Adam\'s Golf Club')

# Importing views registers the routes on api_bp via decorators.
from . import views  # noqa: E402,F401
